### ISSUE TITLE
[Question] Unrecognized characters

### ISSUE THREAD

**Issue by lf-araujo** [laaksomavrick/swift-matrix#1]
I am attempting to make your code work under Linux and for this aim I made it comply to SPM. The code is now working, however it is spitting some unrecognized characters. I suppose this is related to the fact that I had to change all instances of arc4random to Glibc.random(), the latter returns Int() and the former Uint. So I believe this change is sending characters out of bound.

The file in question is here: https://github.com/lf-araujo/SwiftMatrix/blob/master/Sources/SwiftMatrix/Matrix.swift

- Could you please suggest me where to look at? I was unable to sort this issue out.

Many thanks.

**Comment by laaksomavrick** [comment]
Does glibc.random ever return negative integers (ie, they're signed)? This may be the issue. The `draw_new_stream` function is where these characters are being added I believe (it's been a while since I've looked at this code, you can see it's generating an int within 0 ... 300 however). You'll have to figure out what integers correspond to valid characters for your environment :)

**Comment by lf-araujo** [comment]
Thanks, will look into it.

**Comment by lf-araujo** [comment]
Oh, also notice that in last commit I am using the new Random API from Swift 4.2. The code may even work on Macs now. Will look into the possibility of negative numbers being the issue.

**Comment by laaksomavrick** [comment]
Let me know how it goes and if I can be of any more help!
